apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30092
        hostPort: 30092
      - containerPort: 30093
        hostPort: 30093
      - containerPort: 30094
        hostPort: 30094
      - containerPort: 30042
        hostPort: 30042
      - containerPort: 30043
        hostPort: 30043
      - containerPort: 30044
        hostPort: 30044
  - role: worker
  - role: worker
  - role: worker
