apiVersion: v1
kind: Service
metadata:
  namespace: cassandra
  name: cassandra-headless
  labels:
    app: cassandra
spec:
  ports:
    - port: 9042
      name: cql
    - port: 7000
      name: intra-node
  clusterIP: None
  selector:
    app: cassandra
---
apiVersion: v1
kind: Service
metadata:
  namespace: cassandra
  name: cassandra-client
spec:
  type: NodePort
  ports:
    - port: 9042
      targetPort: 9042
      nodePort: 30042 
      name: cql
  selector:
    app: cassandra 
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: cassandra
  name: cassandra
spec:
  serviceName: "cassandra-headless"
  replicas: 3
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      terminationGracePeriodSeconds: 180
      containers:
        - name: cassandra
          image: "cassandra:4.1.5"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 9042
              name: cql
          env:
            - name: CASSANDRA_CLUSTER_NAME
              value: "my-cluster"
            - name: CASSANDRA_DC
              value: "my-datacenter-1"
            - name: CASSANDRA_ENDPOINT_SNITCH
              value: "GossipingPropertyFileSnitch"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CASSANDRA_SEEDS
              value: "cassandra-0.cassandra-headless.$(POD_NAMESPACE).svc.cluster.local"
            - name: MAX_HEAP_SIZE
              value: "1024M"
            - name: HEAP_NEWSIZE
              value: "256M"
            - name: CASSANDRA_START_RPC
              value: "true"
            - name: CASSANDRA_RPC_ADDRESS
              value: "0.0.0.0"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: CASSANDRA_LISTEN_ADDRESS
              value: "$(POD_IP)"
            - name: CASSANDRA_BROADCAST_ADDRESS
              value: "$(POD_IP)"
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - "nodetool status | grep -w UN"
            initialDelaySeconds: 120
            periodSeconds: 120
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - "nodetool status | grep -w UN"
            initialDelaySeconds: 180
            periodSeconds: 120
            timeoutSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: cassandra-data
              mountPath: /var/lib/cassandra
  volumeClaimTemplates:
    - metadata:
        name: cassandra-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi